objc: true
clean: true
sdk: appletvsimulator

theme: ../../Themes/apple

module: AppCenterCrashes
module_version: 3.3.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Crashes.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/tvOS/AppCenterCrashes.framework/Headers/AppCenterCrashes.h
framework_root: ../../../AppCenter-SDK-Apple/tvOS/
exclude: [../../../AppCenter-SDK-Apple/tvOS/AppCenterCrashes.framework/Headers/MSService.h, ../../../AppCenter-SDK-Apple/tvOS/AppCenterCrashes.framework/Headers/MSServiceAbstract.h]

root_url: https://docs.microsoft.com/appcenter/sdk/ios
github_url: https://github.com/microsoft/appcenter-sdk-apple
github_file_prefix: "https://github.com/microsoft/appcenter-sdk-apple"

skip_undocumented: true

output: Generated/
