
<xml version="1.0" encoding="UTF-8"?>
<DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConsentText</key>
	<dict>
		<key>default</key>
		<string>The Accounts and Authentication Logging profile generates files that allow Apple to troubleshoot issues with your accounts, including your configured accounts such as iCloud, Facebook, Twitter and Gmail, on your iOS device. The generated log files include information about your accounts and device and may contain information that could be considered your personal information, including account information of your configured accounts, such as the username and email address associated with the account; your device information, such as the serial number, phone number, other unique identifiers associated with the device, and user device metadata; Apple ID authentication information, such as when you are asked to authenticate, whether the authentication succeeded or failed, and your authentication activity on other devices; Apple ID URL traffic information, such as the URLs of requests going to iCloud, Game Center and other Apple ID-based services; timestamps; app identifiers; and iCloud record identifiers. This profile will expire after 3 days.
                    
You will be able to turn on and off logging at any time while the Profile is installed, and will be able to review the log files on your computer prior to sending them to Apple. To turn off logging on your iOS device, open Settings, tap "General," tap "Profiles," tap "Accounts and Authentication Logging," and tap "Delete Profile."
                    
By enabling this diagnostic tool and sending a copy of the generated files to Apple, you are consenting to Apple's use of your information in accordance with its privacy policy (http://www.apple.com/legal/privacy).
</string>
	</dict>
	<key>DurationUntilRemoval</key>
	<real>259200</real>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadDescription</key>
			<string>Enables Accounts and Authentication debug logging</string>
			<key>PayloadDisplayName</key>
			<string>Accounts and Authentication Logging</string>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>com.apple.accounts.debuglogging</string>
			<key>PayloadOrganization</key>
			<string>Apple Inc.</string>
			<key>PayloadType</key>
			<string>com.apple.system.logging</string>
			<key>PayloadUUID</key>
			<string>3FD779E1-FACF-42A6-A4B2-1A94A85D57E9</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
			<key>Subsystems</key>
			<dict>
				<key>com.apple.accounts</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Oversize-Messages</key>
						<true/>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.appleaccount</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Oversize-Messages</key>
						<true/>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.authkit</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Oversize-Messages</key>
						<true/>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.cdp</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.dataaccess</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Oversize-Messages</key>
						<true/>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Info</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.family</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.followup</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.iCloudQuota</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.icloudnotification</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Oversize-Messages</key>
						<true/>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.persona</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.remoteui</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Oversize-Messages</key>
						<true/>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
				<key>com.apple.social</key>
				<dict>
					<key>DEFAULT-OPTIONS</key>
					<dict>
						<key>Enable-Private-Data</key>
						<true/>
						<key>Level</key>
						<dict>
							<key>Enable</key>
							<string>Debug</string>
							<key>Persist</key>
							<string>Debug</string>
						</dict>
						<key>TTL</key>
						<dict>
							<key>Debug</key>
							<integer>3</integer>
							<key>Default</key>
							<integer>3</integer>
							<key>Info</key>
							<integer>3</integer>
						</dict>
					</dict>
				</dict>
			</dict>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Enables Accounts and Authentication debug logging</string>
	<key>PayloadDisplayName</key>
	<string>Accounts and Authentication Logging</string>
	<key>PayloadIdentifier</key>
	<string>com.apple.accounts.debuglogging</string>
	<key>PayloadOrganization</key>
	<string>Apple Inc.</string>
	<key>PayloadRebootSuggested</key>
	<true/>
	<key>PayloadRemovalDisallowed</key>
	<false/>
	<key>PayloadScope</key>
	<string>system</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>FB33C6F9-7855-47D7-95C3-58115C6B3C06</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
	<key>RemovalDate</key>
	<date>2022-08-01T07:00:00Z</date>
</dict>
</plist>
	
Apple Inc.Apple Certification Authority
Apple Root CA
130524174337Z
280524174337Z01>
Apple Application Integration 2 Certification Authority
Apple Certification Authority

Apple Inc. "en.US"
