#import <Foundation/Foundation.h>

/**
* Avalanche.Ingestion
* Microsoft Avalanche Ingestion REST API.
*
* OpenAPI spec version: 2016-06-14
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "AVALog.h"


@protocol AVADeviceLog
@end

@interface AVADeviceLog : AVALog

@property(nonatomic) NSString* sdkVersion;
/* Device model (example: iPad2,3).  
 */
@property(nonatomic) NSString* model;
/* Device manufacturer (example: HTC).  
 */
@property(nonatomic) NSString* oemName;
/* OS name (example: iOS).  
 */
@property(nonatomic) NSString* osName;
/* OS version (example: 9.3.0).  
 */
@property(nonatomic) NSString* osVersion;
/* API level when applicable like in Android (example: 15).  [optional]
 */
@property(nonatomic) NSNumber* osApiLevel;
/* Language code (example: en_US).  
 */
@property(nonatomic) NSString* locale;
/* The offset in minutes from UTC for the device time zone, including daylight savings time.  
 */
@property(nonatomic) NSNumber* timeZoneOffset;
/* Screen size of the device in pixels (example: 640x480).  
 */
@property(nonatomic) NSString* screenSize;
/* Application version name.  
 */
@property(nonatomic) NSString* appVersion;
/* Carrier name (for mobile devices).  [optional]
 */
@property(nonatomic) NSString* carrierName;
/* Carrier country code (for mobile devices).  [optional]
 */
@property(nonatomic) NSString* carrierCountry;

@end
