objc: true
clean: true
sdk: macosx

theme: ../../Themes/apple

module: AppCenterAuth
module_version: 2.3.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Auth.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/macOS/AppCenterAuth.framework/Headers/AppCenterAuth.h
framework_root: ../../../AppCenter-SDK-Apple/macOS/
exclude: [../../../AppCenter-SDK-Apple/macOS/AppCenterAuth.framework/Headers/MSService.h, ../../../AppCenter-SDK-Apple/macOS/AppCenterAuth.framework/Headers/MSServiceAbstract.h]

root_url: https://docs.microsoft.com/appcenter/sdk/macos
github_url: https://github.com/microsoft/appcenter-sdk-apple
github_file_prefix: "https://github.com/microsoft/appcenter-sdk-apple"

skip_undocumented: true

output: Generated/
