objc: true
clean: true
sdk: iphonesimulator

theme: ../Themes/apple

module: MobileCenter
module_version: 0.6.1
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/MobileCenter.md
documentation: ../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../MobileCenter-SDK-iOS/MobileCenter.framework/Headers/MobileCenter.h
framework_root: ../../MobileCenter-SDK-iOS/

root_url: http://docs.mobile.azure.com/sdk/ios
github_url: https://github.com/Microsoft/mobile-center-sdk-ios
github_file_prefix: "https://github.com/Microsoft/mobile-center-sdk-ios"

skip_undocumented: true

output: Generated/
