objc: true
clean: true
sdk: iphonesimulator

theme: ../Themes/apple

module: Crashes
module_version: 1.0.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Crashes.md
documentation: ../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../Products/SonomaCrashes/SonomaCrashes.framework/Headers/SonomaCrashes.h
framework_root: ../../Products/SonomaCrashes
exclude: [../../Products/SonomaCrashes/SonomaCrashes.framework/Headers/SNMFeature.h, ../../Products/SonomaCrashes/SonomaCrashes.framework/Headers/SNMFeatureAbstract.h]

root_url: http://test.com/sdk/ios/1.0.0
github_url: https://github.com/Microsoft/Sonoma-SDK-iOS
github_file_prefix: "https://github.com/Microsoft/Sonoma-SDK-iOS"

skip_undocumented: true

output: Generated/
