objc: true
clean: true
sdk: iphonesimulator

theme: ../Themes/apple

module: Crashes
module_version: 1.0.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Crashes.md
documentation: ../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../AvalancheCrashes/AvalancheCrashes/AvalancheCrashes.h
framework_root: ../../AvalancheCrashes

root_url: http://test.com/sdk/ios/1.0.0
github_url: https://github.com/Microsoft/AvalancheSDK-iOS
github_file_prefix: "https://github.com/Microsoft/AvalancheSDK-iOS"

skip_undocumented: true

output: Generated/
