objc: true
clean: true
sdk: macosx

theme: ../../Themes/apple

module: AppCenterPush
module_version: 1.13.1
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Push.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/macOS/AppCenterPush.framework/Headers/AppCenterPush.h
framework_root: ../../../AppCenter-SDK-Apple/macOS/
exclude: [../../../AppCenter-SDK-Apple/macOS/AppCenterPush.framework/Headers/MSService.h, ../../../AppCenter-SDK-Apple/macOS/AppCenterPush.framework/Headers/MSServiceAbstract.h]

root_url: https://docs.microsoft.com/appcenter/sdk/macos
github_url: https://github.com/Microsoft/AppCenter-SDK-Apple
github_file_prefix: "https://github.com/Microsoft/AppCenter-SDK-Apple"

skip_undocumented: true

output: Generated/
