#!/bin/bash

# Copy LICENSE, README and CHANGELOG
cp LICENSE $FRAMEWORKS_ZIP_FOLDER
cp README.md $FRAMEWORKS_ZIP_FOLDER
cp CHANGELOG.md $FRAMEWORKS_ZIP_FOLDER

# Zip the folder
zip -r $FRAMEWORKS_ZIP_FILENAME $FRAMEWORKS_ZIP_FOLDER
