objc: true
clean: true
sdk: iphonesimulator

theme: ../Themes/apple

module: Avalanche
module_version: 1.0.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Avalanche.md
documentation: ../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../AvalancheHub/AvalancheHub/AvalancheHub.h
framework_root: ../../AvalancheHub/

root_url: http://test.com/sdk/ios/1.0.0
github_url: https://github.com/Microsoft/AvalancheSDK-iOS
github_file_prefix: "https://github.com/Microsoft/AvalancheSDK-iOS"

skip_undocumented: false

output: Generated/
