pr:
- master
- develop
- feature/*

variables:
  Configuration: Debug
  SDK:

jobs:
- template: analyze-and-test-template.yml
  parameters:
    platform: iOS
    modules: [ AppCenter, AppCenterAnalytics, AppCenterCrashes, AppCenterDistribute ]


