objc: true
clean: true
sdk: macosx

theme: ../../Themes/apple

module: AppCenter
module_version: 3.3.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/AppCenter.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/macOS/AppCenter.framework/Headers/AppCenter.h
framework_root: ../../../AppCenter-SDK-Apple/macOS/

root_url: https://docs.microsoft.com/appcenter/sdk/macos
github_url: https://github.com/microsoft/appcenter-sdk-apple
github_file_prefix: "https://github.com/microsoft/appcenter-sdk-apple"

skip_undocumented: true

output: Generated/
